Repository kurogee/hitokuchi.github.io, pull requests merged in 2023-11, with the labels that each got.

#66 不適切なコンテンツを簡単に報告できる
  ja-JP/index.html
  note/index.html
  review/index.html
Labels: ちょっと追加

#72 Alpha版からBeta番へ移す
  404.html
  admin_room/image/2023_11_12_ICHOU.webp
  admin_room/index.html
  forum/forums/common.js
  forum/forums/english_forum.html
  forum/forums/forum_style.css
  forum/forums/main_forum.html
  forum/style_by_jquery.js
  ja-JP/index.html
  jquery-3.7.1.min.js
  pagestyle.css
  point/games/mine/index.html
  point/games/mine/script/game.js
  point/index.html
  tool_icon/close_element.webp
  tool_icon/open_element.webp
Labels: ちょっと追加

#75 微細な本バージョン更新
  forum/forums/game_forum.html
  forum/forums/hitokoto_forum.html
  forum/forums/it_forum.html
  forum/forums/main_forum.html
  forum/forums/outdoor_forum.html
  forum/forums/programming_forum.html
  forum/forums/shiritori_forum.html
  forum/forums/study_forum.html
  ja-JP/index.html
  point/games/mine/index.html
  point/games/mine/script/game.js
Labels: バグ修正, ちょっと追加

#76 緊急修正
  frame/Frame_ribbon.webp
  frame/Frame_snow.webp
  frame/Frame_toon.webp
  point/games/mine/script/game.js
  point/index.html
Labels: バグ修正, ヘルプがほしい, 間違っているコード

#77 マインスイーパの緊急修正
  frame/Frame_ribbon.webp
  frame/Frame_snow.webp
  frame/Frame_toon.webp
  point/games/mine/script/game.js
  point/index.html
Labels: バグ修正, 間違っているコード

#78 色々追加した
  config.js
  forum/index.html
  frame/Frame_flower.webp
  ja-JP/send.html
  ja-JP/send_message.js
  mail/index.html
  note/index.html
  pagestyle.css
  point/games/mine/script/game.js
  point/index.html
  point/point.js
  premium/index.html
  review/index.html
Labels: バグ修正, 新機能, 中・小規模更新

#80 [緊急]色が変わらないバグを修正
  ja-JP/send_message.js
Labels: バグ修正, 緊急修正, 中・小規模更新

#81 [緊急]色が変わらないバグを修正
  ja-JP/send_message.js
Labels: バグ修正, 中・小規模更新

#82 更新20231124
  config.js
  ja-JP/send.html
  ja-JP/send_message.js
  mail/config.js
  mail/index.html
  mail/pagestyle.css
  mail/signup.html
  note/config.js
  note/index.html
  note/read.html
  note/spread.html
  note/write.html
  note/write_note.js
  pagestyle.css
  point/index.html
  premium/index.html
  tos/index.html
Labels: 新機能, ちょっと追加, 中・小規模更新

#83 hitokuchiの本バージョン更新(20231125)
  config.js
  ja-JP/send.html
  ja-JP/send_message.js
  mail/config.js
  mail/index.html
  mail/pagestyle.css
  mail/signup.html
  note/config.js
  note/index.html
  note/read.html
  note/spread.html
  note/write.html
  note/write_note.js
  pagestyle.css
  point/index.html
  premium/index.html
  tos/index.html
Labels: 新機能, 本公開前評価, ちょっと追加, 中・小規模更新

#84 デザイン変更
  forum/forums/anime_forum.html
  forum/forums/common.js
  forum/forums/forum_style.css
  index_icon/Forum_icon.webp
  index_icon/Mail_icon.webp
  index_icon/Note_icon.webp
  index_icon/Review_icon.webp
  ja-JP/index.html
  ja-JP/mes.html
  ja-JP/send.html
  mail/pagestyle.css
  pagestyle.css
  point/games/mine/index.html
  point/index.html
  premium/index.html
Labels: 大規模更新

#85 デザイン変更 ( Main )
  forum/forums/anime_forum.html
  forum/forums/common.js
  forum/forums/forum_style.css
  index_icon/Forum_icon.webp
  index_icon/Mail_icon.webp
  index_icon/Note_icon.webp
  index_icon/Review_icon.webp
  ja-JP/index.html
  ja-JP/mes.html
  ja-JP/send.html
  mail/pagestyle.css
  pagestyle.css
  point/games/mine/index.html
  point/index.html
  premium/index.html
Labels: 本公開前評価, 大規模更新

#87 色々なデザイン変更
  404.html
  forum/forums/anime_forum.html
  forum/forums/forum_style.css
  forum/forums/game_forum.html
  forum/forums/hitokoto_forum.html
  forum/forums/it_forum.html
  forum/forums/main_forum.html
  forum/forums/outdoor_forum.html
  forum/forums/programming_forum.html
  forum/forums/shiritori_forum.html
  forum/forums/study_forum.html
  ja-JP/index.html
  mail/index.html
  mail/pagestyle.css
  pagestyle.css
  point/account_login.html
Labels: ちょっと追加, 中・小規模更新

#88 色々なデザイン変更 ( Main )
  404.html
  forum/forums/anime_forum.html
  forum/forums/forum_style.css
  forum/forums/game_forum.html
  forum/forums/hitokoto_forum.html
  forum/forums/it_forum.html
  forum/forums/main_forum.html
  forum/forums/outdoor_forum.html
  forum/forums/programming_forum.html
  forum/forums/shiritori_forum.html
  forum/forums/study_forum.html
  ja-JP/index.html
  mail/index.html
  mail/pagestyle.css
  pagestyle.css
  point/account_login.html
Labels: 本公開前評価, ちょっと追加, 中・小規模更新

#89 スマホ対応7
  en-US/index.html
  forum/forums/english_forum.html
  ja-JP/flame/Flame_coffee.webp
  ja-JP/flame/Flame_himawari.webp
  ja-JP/flame/Flame_kusabana.webp
  ja-JP/flame/Flame_mono.webp
  ja-JP/flame/Flame_onpu.webp
  ja-JP/flame/Flame_star.webp
  ja-JP/index.html
  mail/index.html
  mail/pagestyle.css
  pagestyle.css
  premium/index.html
  review/sendreview.html
  sitemap.xml
Labels: ちょっと追加, 中・小規模更新

#90 スマホ対応7 ( Main )
  en-US/index.html
  forum/forums/english_forum.html
  ja-JP/flame/Flame_coffee.webp
  ja-JP/flame/Flame_himawari.webp
  ja-JP/flame/Flame_kusabana.webp
  ja-JP/flame/Flame_mono.webp
  ja-JP/flame/Flame_onpu.webp
  ja-JP/flame/Flame_star.webp
  ja-JP/index.html
  mail/index.html
  mail/pagestyle.css
  pagestyle.css
  premium/index.html
  review/sendreview.html
  sitemap.xml
Labels: 本公開前評価, ちょっと追加, 中・小規模更新

#92 色々追加&不要部分を削除
  config.js
  forum/forums/common.js
  forum/forums/news_forum.html
  forum/index.html
  ja-JP/get_massage.js
  note/write.html
  pagestyle.css
Labels: 本公開前評価, ちょっと追加, 中・小規模更新

#93 iPad対応
  forum/forums/anime_forum.html
  forum/forums/english_forum.html
  forum/forums/game_forum.html
  forum/forums/hitokoto_forum.html
  forum/forums/it_forum.html
  forum/forums/main_forum.html
  forum/forums/news_forum.html
  forum/forums/outdoor_forum.html
  forum/forums/programming_forum.html
  forum/forums/shiritori_forum.html
  forum/forums/study_forum.html
  mail/pagestyle.css
  pagestyle.css
Labels: バグ修正, 中・小規模更新

#94 iPad対応 ( Main )
  forum/forums/anime_forum.html
  forum/forums/english_forum.html
  forum/forums/game_forum.html
  forum/forums/hitokoto_forum.html
  forum/forums/it_forum.html
  forum/forums/main_forum.html
  forum/forums/news_forum.html
  forum/forums/outdoor_forum.html
  forum/forums/programming_forum.html
  forum/forums/shiritori_forum.html
  forum/forums/study_forum.html
  mail/pagestyle.css
  pagestyle.css
Labels: バグ修正, 本公開前評価, 中・小規模更新

#95 色々追加etc
  note/write.html
  pagestyle.css
  point/games/slider/index.html
  point/games/slider/script/game.js
  point/games/typing/js/game.js
  point/icons/mine.webp
  point/icons/slide.webp
  point/icons/typing.webp
  point/index.html
  premium/index.html
Labels: 既存の機能の改善についての相談, ちょっと追加, 中・小規模更新

#96 色々追加 - 主にゲーム系(20231128)
  note/write.html
  pagestyle.css
  point/games/slider/index.html
  point/games/slider/script/game.js
  point/games/typing/js/game.js
  point/icons/mine.webp
  point/icons/slide.webp
  point/icons/typing.webp
  point/index.html
  premium/index.html
Labels: 本公開前評価, ちょっと追加, 中・小規模更新
