Repository kurogee/hitokuchi.github.io, pull requests merged in 2023-10, with the labels that each got.

#29 英語版の機能充実
  admin_room/index.html
  dot/mes.html
  dot/send.html
  en-US/index.html
  en-US/mes.html
  en-US/send.html
  ja-JP/account.html
  ja-JP/account_login.html
  ja-JP/getpoint.html
  ja-JP/mes.html
  ja-JP/send.html
  mail/signup.html
  note/index.html
  note/read.html
  note/spread.html
  note/write.html
  pagestyle.css
  review/sendreview.html
  tos/index.html
Labels: enhancement

#30 スマホ対応
  ja-JP/index.html
  pagestyle.css
Labels: バグ修正

#31 スマホ対応2
  ja-JP/index.html
  mail/pagestyle.css
  review/index.html
Labels: バグ修正

#32 スマホ対応3
  en-US/index.html
  ja-JP/index.html
  pagestyle.css
  review/watchreview.html
Labels: バグ修正

#35 スマホ対応5
  ja-JP/mes.html
  ja-JP/send.html
  note/read.html
Labels: バグ修正

#36 main(公開)バージョンの更新
  admin_room/index.html
  dot/mes.html
  dot/send.html
  en-US/index.html
  en-US/mes.html
  en-US/send.html
  index_icon/Mail_icon.webp
  index_icon/Note_icon.webp
  index_icon/Review_icon.webp
  ja-JP/account.html
  ja-JP/account_login.html
  ja-JP/getpoint.html
  ja-JP/index.html
  ja-JP/mes.html
  ja-JP/point.js
  ja-JP/send.html
  mail/index.html
  mail/pagestyle.css
  mail/signup.html
  note/index.html
  note/read.html
  note/spread.html
  note/write.html
  pagestyle.css
  review/index.html
  review/sendreview.html
  review/watchreview.html
  tos/index.html
Labels: 本公開前評価

#37 メッセージコマンドの追加
  en-US/send.html
  en-US/send_message.js
  ja-JP/point.js
  ja-JP/send.html
  ja-JP/send_message.js
  pagestyle.css
  point/account.html
  point/account_login.html
  point/auth.html
  point/getpoint.html
  point/index.html
  point/point.js
Labels: 新機能

#38 見やすさ向上
  ja-JP/index.html
Labels: バグ修正

#40 キャッチコピー追加
  note/index.html
  note/write.html
  point/auth.html
  point/point.js
  review/index.html
  review/sendreview.html
Labels: 新機能

#41 Mailのボタン化
  mail/index.html
  mail/pagestyle.css
  note/index.html
  point/auth.html
  point/getpoint.html
  point/point.js
  review/watchreview.html
Labels: ちょっと追加

#42 ポイントのデザイン修正
  config.js
  ja-JP/get_massage.js
  ja-JP/index.html
  ja-JP/mes.html
  pagestyle.css
  point/account.html
  point/account_login.html
  point/auth.html
  point/games/typing/index.html
  point/games/typing/js/game.js
  point/games/typing/key_sound.mp3
  point/index.html
  point/point.js
Labels: ちょっと追加

#43 README.md 追加
  README.md
Labels: 新機能, 色々相談

#46 本バージョンの更新
  404-image.webp
  404.html
  404.md
  README.md
  config.js
  dot/index.html
  dot/mes.html
  dot/send.html
  en-US/get_massage.js
  en-US/index.html
  en-US/mes.html
  en-US/send.html
  en-US/send_message.js
  index.html
  ja-JP/get_massage.js
  ja-JP/index.html
  ja-JP/mes.html
  ja-JP/point.js
  ja-JP/send.html
  ja-JP/send_message.js
  mail/index.html
  mail/pagestyle.css
  mail/signup.html
  note/index.html
  note/read.html
  note/spread.html
  note/write.html
  pagestyle.css
  point/account.html
  point/account_login.html
  point/games/typing/index.html
  point/games/typing/js/game.js
  point/games/typing/key_sound.mp3
  point/index.html
  point/point.js
  review/index.html
  review/sendreview.html
  review/watchreview.html
  tos/index.html
Labels: 本公開前評価

#49 404ページのパスを修正(Main)
  404.html
Labels: バグ修正, 本公開前評価

#52 文字が太字にならないバグを修正(Main)
  config.js
  note/index.html
  pagestyle.css
Labels: バグ修正, 本公開前評価

#54 「開発中」の削除 ( Main )
  README.md
  forum/index.html
  notification/index.html
Labels: 本公開前評価, ちょっと追加

#55 掲示板プロジェクトをalphaブランチへ移動する
  forum/forum_script.js
  forum/forums/common.js
  forum/forums/forum_style.css
  forum/forums/main_forum.html
  forum/index.html
Labels: 新機能, 色々相談

#56 いろいろデザイン変更
  README.md
  forum/forums/forum_style.css
  forum/forums/main_forum.html
  forum/index.html
  note/read.html
  pagestyle.css
Labels: ちょっと追加

#58 indexにボタンを追加
  forum/forum_script.js
  forum/forums/common.js
  forum/forums/forum_style.css
  forum/forums/main_forum.html
  forum/index.html
  index_icon/Forum_icon.webp
  ja-JP/index.html
  note/read.html
  pagestyle.css
Labels: バグ修正, ちょっと追加

#59 indexにボタンを追加 ( Main )
  forum/forum_script.js
  forum/forums/common.js
  forum/forums/forum_style.css
  forum/forums/main_forum.html
  forum/index.html
  index_icon/Forum_icon.webp
  ja-JP/index.html
  note/read.html
  pagestyle.css
Labels: バグ修正, 本公開前評価, ちょっと追加

#60 スマホ対応6
  forum/forum_script.js
  forum/forums/anime_forum.html
  forum/forums/common.js
  forum/forums/game_forum.html
  forum/forums/programming_forum.html
  forum/forums/study_forum.html
  forum/index.html
  ja-JP/index.html
  pagestyle.css
Labels: バグ修正

#61 スマホ対応6 ( Main )
  forum/forum_script.js
  forum/forums/anime_forum.html
  forum/forums/common.js
  forum/forums/game_forum.html
  forum/forums/programming_forum.html
  forum/forums/study_forum.html
  forum/index.html
  ja-JP/index.html
  pagestyle.css
Labels: バグ修正, 本公開前評価

#62 掲示板説明追加
  README.md
Labels: ちょっと追加

#63 掲示板説明追加 ( Main )
  README.md
Labels: 本公開前評価, ちょっと追加
