Repository kurogee/hitokuchi.github.io, pull requests merged in 2024-01, with the labels that each got.

#112 betaの更新
  ja-JP/send.html
  mail/index.html
  note/write_note.js
  pagestyle.css
  review/sendreview.html
Labels: ちょっと追加, 中・小規模更新

#113 20240119 - 本バージョンの更新
  ja-JP/send.html
  mail/index.html
  note/write_note.js
  pagestyle.css
  review/sendreview.html
Labels: 本公開前評価, ちょっと追加, 中・小規模更新

#114 いろいろ変更
  forum/index.html
  ja-JP/index.html
  ja-JP/send.html
  mail/index.html
  mail/pagestyle.css
  note/index.html
  note/write.html
  pagestyle.css
  point/account_login.html
  point/index.html
  premium/index.html
  review/index.html
Labels: 新機能, 大規模更新

#115 ちょっと便利なアップデート ( Main )
  forum/index.html
  ja-JP/index.html
  ja-JP/send.html
  mail/index.html
  mail/pagestyle.css
  note/index.html
  note/write.html
  pagestyle.css
  point/account_login.html
  point/index.html
  premium/index.html
  review/index.html
Labels: 新機能, 本公開前評価, 大規模更新

#117 バグの修正と新機能
  ja-JP/index.html
  ja-JP/mes.html
  ja-JP/send.html
  pagestyle.css
  point/games/mine/index.html
  point/games/slider/index.html
  point/games/typing/index.html
  point/gift_point.html
  point/index.html
  point/point.js
  premium/index.html
Labels: バグ修正, 新機能, 中・小規模更新
