Repository kurogee/hitokuchi.github.io, pull requests merged in 2024-02, with the labels that each got.

#118 問題の修正と新機能のアップデート ( Main )
  ja-JP/index.html
  ja-JP/mes.html
  ja-JP/send.html
  pagestyle.css
  point/games/mine/index.html
  point/games/slider/index.html
  point/games/typing/index.html
  point/gift_point.html
  point/index.html
  point/point.js
  premium/index.html
Labels: バグ修正, 新機能, 本公開前評価, 中・小規模更新

#119 [緊急] X共有のURL変更
  ja-JP/index.html
Labels: 緊急修正

#120 [緊急] X共有のURLを変更
  ja-JP/index.html
Labels: 本公開前評価, 緊急修正

#121 修正と表示の変更
  index_icon/Forum_icon.webp
  index_icon/Mail_icon.webp
  index_icon/Note_icon.webp
  index_icon/Review_icon.webp
  ja-JP/index.html
  ja-JP/send.html
  pagestyle.css
  point/index.html
  premium/index.html
Labels: 新機能, ちょっと追加, 中・小規模更新

#122 見やすくて美しいアップデート ( Main )
  index_icon/Forum_icon.webp
  index_icon/Mail_icon.webp
  index_icon/Note_icon.webp
  index_icon/Review_icon.webp
  ja-JP/index.html
  ja-JP/send.html
  pagestyle.css
  point/index.html
  premium/index.html
Labels: 新機能, 本公開前評価, ちょっと追加, 中・小規模更新

#124 Blueskyのドメイン設定用のファイル
  .well-known/atproto-did
Labels: 本公開前評価, ちょっと追加
